package hu.hm.szititourbackend.util

object MessageConstants {

    //! SUCCESS MESSAGES:
    const val TOPIC_NOTIFICATION_SENT = "TOPIC_NOTIFICATION_SENT"
    const val DIRECT_NOTIFICATION_SENT = "DIRECT_NOTIFICATION_SENT"
    const val TEAM_DELETE_SUCCESS = "TEAM_DELETE_SUCCESS"
    const val LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
    const val EMAIL_VERIFICATION_FAILED = "EMAIL_VERIFICATION_FAILED"
    const val EMAIL_VERIFIED = "EMAIL_VERIFIED"
    const val REGISTER_SUCCESS = "REGISTER_SUCCESS"


    //! ERROR MESSAGES:
    const val TEAM_NOT_VERIFIED = "TEAM_NOT_VERIFIED"
    const val REQUEST_METHOD_NOT_SUPPORTED = "REQUEST_METHOD_NOT_SUPPORTED"
    const val MISSING_REQUEST_VALUE = "MISSING_REQUEST_VALUE"
    const val GAME_TITLE_TAKEN = "GAME_TITLE_TAKEN"

    const val EMAIL_EMPTY = "EMAIL_EMPTY"
    const val GOOGLE_NOT_VERIFIED = "GOOGLE_NOT_VERIFIED"
    const val PASSWORD_EMPTY = "PASSWORD_EMPTY"
    const val WRONG_PASSWORD = "WRONG_PASSWORD"
    const val EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    const val IMG_FORMAT_NOT_SUPPORTED = "IMG_FORMAT_NOT_SUPPORTED"
    const val IMG_COMPRESSION_NOT_SUPPORTED = "IMG_COMPRESSION_NOT_SUPPORTED"
    const val GAME_GAMEID_QUESTIONID_NULL = "GAME_GAMEID_QUESTIONID_NULL"
    const val GAME_NAME_TAKEN = "GAME_NAME_TAKEN"
    const val GAME_NOT_FOUND = "GAME_NOT_FOUND"
    const val INVALID_NOTIFICATION = "INVALID_NOTIFICATION"
    const val EMAIL_SEND_FAILED_TEMPLATE_NULL = "EMAIL_SEND_FAILED_TEMPLATE_NULL"

    const val AUTH_TOKENID_NOT_FOUND = "AUTH_TOKENID_NOT_FOUND"
    const val AUTH_TOKEN_BAD_RESOURCE_ID = "AUTH_TOKEN_BAD_RESOURCE_ID"
    const val GOOGLE_VALIDATION_FAILED = "GOOGLE_VALIDATION_FAILED"
    const val INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN"
    const val AUTH_EMPTY_TOKENID = "AUTH_EMPTY_TOKENID"
    const val AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    const val EMAIL_INVALID = "EMAIL_INVALID"
    const val PASSWORD_INVALID = "PASSWORD_INVALID"
    const val EMAIL_TAKEN = "EMAIL_TAKEN"
    const val EMPTY_CREDENTIALS = "EMPTY_CREDENTIALS"
    const val TEAM_INACTIVE = "TEAM_INACTIVE"
    const val AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    const val AUTH_INVALID_TOKEN_TYPE = "AUTH_INVALID_TOKEN_TYPE"
    const val PLACE_NOT_FOUND_CONVERT = "PLACE_NOT_FOUND_CONVERT"

    const val VERIFICATION_FAILED = "VERIFICATION_FAILED"
    const val RESOURCE_IMG_NOT_FOUND = "RESOURCE_IMG_NOT_FOUND"
    const val RESOURCE_DIRECTORY_NOT_FOUND = "RESOURCE_DIRECTORY_NOT_FOUND"
    const val QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND"

    const val PLACE_NOT_FOUND = "PLACE_NOT_FOUND"
    const val GAME_INACTIVE = "GAME_INACTIVE"
    const val APPLICATION_NOT_ACCEPTED = "APPLICATION_NOT_ACCEPTED"
    const val TEAM_NOT_FOUND = "TEAM_NOT_FOUND"
    const val CANNOT_CANCEL_REFUSED = "CANNOT_CANCEL_REFUSED"
    const val CANNOT_CANCEL_ACTIVE = "CANNOT_CANCEL_ACTIVE"
    const val TEAM_ALREADY_APPLIED = "TEAM_ALREADY_APPLIED"
    const val CANNOT_APPLY_ACTIVE_GAME = "CANNOT_APPLY_ACTIVE_GAME"
    const val APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND"
    const val ANSWER_NOT_FOUND = "ANSWER_NOT_FOUND"
    const val UNKNOWN = "UNKNOWN"

}